version: '3.9'

services:
    postgres:
        image: 'postgres:13.3'
        restart: always
        volumes:
            - ./data/db:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=admin
        ports:
            - '5432:5432'